stages:
  - build

build-plugin-file:
  stage: build
  image: alpine:latest
  before_script:
    - apt install zip
  script:
    - echo "Hello World"
  tags:
    - docker
#  only:
#    - branch: master
