stages:
  - build

build-plugin-file:
  stage: build
  image: alpine:latest
  before_script:
    - apk add zip
  script:
    - zip addon.zip *
    - mv addon.zip addon.xpi
  artifacts:
    paths:
      - addon.xpi
    expire_in: 1 week
    when: always
  tags:
    - docker
#  only:
#    - branch: master
